const $=id=>document.getElementById(id);
const ui={run:$('run'),sequence:$('sequence'),status:$('status'),seek:$('seek'),play:$('play'),speed:$('speed')};
let payload=null, sequence=null, index=0, playing=false, lastTime=0, carry=0;

function number(value,digits=6){return Number(value).toFixed(digits)}
function scientific(value){return Number(value).toExponential(3)}
function resize(canvas){const dpr=devicePixelRatio||1,r=canvas.getBoundingClientRect();const w=Math.max(1,Math.round(r.width*dpr)),h=Math.max(1,Math.round(r.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);return [c,r.width,r.height]}
function extent(values,pad=.7){let min=Math.min(...values),max=Math.max(...values);if(!Number.isFinite(min)||min===max){min=(min||0)-1;max=(max||0)+1}return [min-pad,max+pad]}
function transform(xRange,yRange,w,h,pad=34){return {x:v=>pad+(v-xRange[0])/(xRange[1]-xRange[0])*(w-pad*2),y:v=>h-pad-(v-yRange[0])/(yRange[1]-yRange[0])*(h-pad*2),pad}}
function axes(c,t,w,h,xLabel,yLabel){c.strokeStyle='#dce5ee';c.lineWidth=1;c.strokeRect(t.pad,t.pad,w-t.pad*2,h-t.pad*2);c.fillStyle='#8b98aa';c.font='10px Microsoft YaHei';c.fillText(xLabel,w-24,h-10);c.fillText(yLabel,10,18)}
function path(c,points,t,color,dash=[]){if(!points.length)return;c.beginPath();points.forEach((p,i)=>(i?c.lineTo(t.x(p[0]),t.y(p[1])):c.moveTo(t.x(p[0]),t.y(p[1]))));c.strokeStyle=color;c.lineWidth=2;c.setLineDash(dash);c.stroke();c.setLineDash([])}

function drawTop(){const [c,w,h]=resize($('top-view'));c.clearRect(0,0,w,h);if(!sequence)return;const samples=sequence.samples, actual=samples.map(s=>s.actual.position), predicted=samples.map(s=>s.predicted.position);const blocks=(payload.world.blocks||[]).map(b=>b.position);const xr=extent([...actual.map(p=>p[0]),...predicted.map(p=>p[0]),...blocks.map(p=>p[0]+.5)]),zr=extent([...actual.map(p=>p[2]),...predicted.map(p=>p[2]),...blocks.map(p=>p[2]+.5)]);const t=transform(xr,zr,w,h);axes(c,t,w,h,'X','Z');c.fillStyle='#5365791e';for(const b of blocks)c.fillRect(t.x(b[0]),t.y(b[2]+1),Math.max(1,t.x(b[0]+1)-t.x(b[0])),Math.max(1,t.y(b[2])-t.y(b[2]+1)));path(c,actual.map(p=>[p[0],p[2]]),t,'#168bd2');path(c,predicted.map(p=>[p[0],p[2]]),t,'#e89036',[6,4]);const s=samples[index];for(const [state,color,dash] of [[s.actual,'#168bd2',[]],[s.predicted,'#e89036',[4,3]]]){const [x,,z]=state.position,half=state.body_width/2;c.strokeStyle=color;c.lineWidth=2;c.setLineDash(dash);c.strokeRect(t.x(x-half),t.y(z+half),t.x(x+half)-t.x(x-half),t.y(z-half)-t.y(z+half));c.setLineDash([])}}
function cumulative(samples,key){const out=[0];for(let i=1;i<samples.length;i++){const a=samples[i-1][key].position,b=samples[i][key].position;out.push(out[i-1]+Math.hypot(b[0]-a[0],b[2]-a[2]))}return out}
function drawSide(){const [c,w,h]=resize($('side-view'));c.clearRect(0,0,w,h);if(!sequence)return;const s=sequence.samples,dist=cumulative(s,'actual'),pd=cumulative(s,'predicted'),ys=[...s.map(x=>x.actual.position[1]),...s.map(x=>x.predicted.position[1])];const t=transform(extent([...dist,...pd],.2),extent(ys,.7),w,h);axes(c,t,w,h,'路程','Y');if(payload.world.floor_y!=null){c.strokeStyle='#7d8b9b66';c.beginPath();c.moveTo(t.x(0),t.y(payload.world.floor_y+1));c.lineTo(t.x(Math.max(...dist,...pd)),t.y(payload.world.floor_y+1));c.stroke()}path(c,s.map((x,i)=>[dist[i],x.actual.position[1]]),t,'#168bd2');path(c,s.map((x,i)=>[pd[i],x.predicted.position[1]]),t,'#e89036',[6,4]);const now=s[index];for(const [state,d,color] of [[now.actual,dist[index],'#168bd2'],[now.predicted,pd[index],'#e89036']]){c.strokeStyle=color;c.lineWidth=2;c.strokeRect(t.x(d)-4,t.y(state.position[1]+state.body_height),8,t.y(state.position[1])-t.y(state.position[1]+state.body_height))}}
function drawError(){const [c,w,h]=resize($('error-view'));c.clearRect(0,0,w,h);if(!sequence)return;const s=sequence.samples,px=s.map(x=>x.error.position_max),vx=s.map(x=>x.error.velocity_max),maximum=Math.max(...px,...vx,1e-15),t=transform([0,Math.max(1,s.length-1)],[-maximum*.08,maximum*1.12],w,h);axes(c,t,w,h,'tick','误差');path(c,px.map((v,i)=>[i,v]),t,'#a960bb');path(c,vx.map((v,i)=>[i,v]),t,'#3c9b76');c.strokeStyle='#35465b55';c.beginPath();c.moveTo(t.x(index),t.y(0));c.lineTo(t.x(index),t.y(maximum));c.stroke();c.fillStyle='#78879a';c.font='9px Consolas';c.fillText(maximum.toExponential(2),t.pad+3,t.pad+10)}

function stateRows(state){return `<dt>位置 X / Y / Z</dt><dd>${state.position.map(v=>number(v)).join(' / ')}</dd><dt>速度 X / Y / Z</dt><dd>${state.velocity.map(v=>number(v)).join(' / ')}</dd><dt>姿态 / 碰撞箱高</dt><dd>${state.pose} / ${number(state.body_height,2)}</dd><dt>在地面 / 冲刺 / 潜行</dt><dd>${state.on_ground?'是':'否'} / ${state.sprinting?'是':'否'} / ${state.sneaking?'是':'否'}</dd>`}
function render(){if(!sequence)return;index=Math.max(0,Math.min(index,sequence.samples.length-1));const s=sequence.samples[index];ui.seek.value=index;$('frame').textContent=`${index} / ${sequence.samples.length-1}`;$('clock').textContent=number(s.t,3)+' s';$('actual-state').innerHTML=stateRows(s.actual);$('predicted-state').innerHTML=stateRows(s.predicted);$('actual-events').textContent=s.actual_events.join('、')||'无';$('predicted-events').textContent=s.predicted_events.join('、')||'无';$('error-now').textContent=`位置 ${scientific(s.error.position_max)} · 速度 ${scientific(s.error.velocity_max)}`;if(s.input){const i=s.input;$('tick-input').textContent=`前后 ${number(i.forward,2)}，左右 ${number(i.strafe,2)}，朝向 ${number(i.movement_yaw_degrees,1)}°${i.jump?'，跳跃':''}${i.sneak?'，潜行':''}${i.sprint?'，冲刺':''}`}else $('tick-input').textContent='连续段起点';drawTop();drawSide();drawError()}
function chooseSequence(){sequence=payload.sequences[Number(ui.sequence.value)]||payload.sequences[0];index=0;ui.seek.max=Math.max(0,sequence.samples.length-1);$('duration').textContent=number(sequence.duration,3)+' s';$('segment-reason').textContent='切段原因：'+sequence.break_reasons.join('、');render()}
async function loadRun(){playing=false;ui.play.textContent='▶ 播放';ui.status.textContent='正在计算整段预测…';try{const r=await fetch('/api/physics/run/'+encodeURIComponent(ui.run.value));if(!r.ok)throw new Error((await r.json()).message||`HTTP ${r.status}`);payload=await r.json();$('tick-count').textContent=payload.summary.tick_count.toLocaleString();$('sequence-count').textContent=payload.summary.sequence_count.toLocaleString();$('position-max').textContent=scientific(payload.summary.position_error_max);$('velocity-max').textContent=scientific(payload.summary.velocity_error_max);$('source').textContent=payload.source;ui.sequence.innerHTML=payload.sequences.map((s,i)=>`<option value="${i}">${s.title} · ${s.tick_count} tick · ${s.duration.toFixed(2)} s</option>`).join('');let longest=0;for(let i=1;i<payload.sequences.length;i++)if(payload.sequences[i].tick_count>payload.sequences[longest].tick_count)longest=i;ui.sequence.value=String(longest);ui.status.textContent=`已按 ${payload.ruleset_id} 计算；默认打开最长连续段，可切换查看其余段`;chooseSequence()}catch(e){ui.status.textContent='载入失败：'+e.message;ui.status.className='error'}}
async function catalog(refresh=false){ui.status.textContent='正在查找封存证据…';const r=await fetch('/api/physics/catalog'+(refresh?'?refresh=1':''));if(!r.ok)throw new Error(`HTTP ${r.status}`);const runs=(await r.json()).runs.filter(x=>x.complete);if(!runs.length)throw new Error('没有找到完整的 B08 / B09 物理证据');ui.run.innerHTML=runs.map(x=>`<option value="${x.id}">${x.title} · ${x.directory.split('/').pop()}</option>`).join('');await loadRun()}
function animation(now){if(playing&&sequence){if(!lastTime)lastTime=now;carry+=(now-lastTime)*Number(ui.speed.value)/50;lastTime=now;const advance=Math.floor(carry);if(advance){carry-=advance;index+=advance;if(index>=sequence.samples.length-1){index=sequence.samples.length-1;playing=false;ui.play.textContent='▶ 播放'}render()}}else lastTime=now;requestAnimationFrame(animation)}
ui.run.addEventListener('change',loadRun);ui.sequence.addEventListener('change',chooseSequence);ui.seek.addEventListener('input',()=>{index=Number(ui.seek.value);render()});$('refresh').addEventListener('click',()=>catalog(true));$('previous').addEventListener('click',()=>{index--;render()});$('next').addEventListener('click',()=>{index++;render()});ui.play.addEventListener('click',()=>{if(index===sequence.samples.length-1)index=0;playing=!playing;ui.play.textContent=playing?'❚❚ 暂停':'▶ 播放';render()});addEventListener('resize',render);addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','SELECT'].includes(e.target.tagName)){e.preventDefault();ui.play.click()}else if(e.code==='ArrowLeft'){index--;render()}else if(e.code==='ArrowRight'){index++;render()}});requestAnimationFrame(animation);catalog().catch(e=>{ui.status.textContent='无法载入：'+e.message;ui.status.className='error'});
